import {gql } from '@apollo/client';

export default {
    createBusiness: gql`
        mutation createBusiness($userID: ID, $ownerID: ID, $businessName:String, $dateEstablished:String, $emailAddress:String, $phoneNumber:String, $website:String, $businessType: String, $businessSubtype: String, $pocketID: ID){
            createBusiness(userID: $userID, ownerID: $ownerID, businessName:$businessName, dateEstablished:$dateEstablished, emailAddress:$emailAddress, phoneNumber:$phoneNumber, website:$website, businessType: $businessType, businessSubtype: $businessSubtype, pocketID:$pocketID) {
                businessID
                businessName
                dateEstablished
                emailAddress
                phoneNumber
                website
                businessType
                businessSubtype
                address{
                  streetName
                  buildingNumber
                  unitNumber
                  city
                  region
                  postalCode
                }
                latitude
                longitude
                businessTags
                stripeID
                description
                hours{
                    Monday {
                      start
                      end
                    }
                    Tuesday{
                      start
                      end
                    }
                    Wednesday{
                      start
                      end
                    }
                    Thursday{
                      start
                      end
                    }
                    Friday{
                      start
                      end
                    }
                    Saturday{
                      start
                      end
                    }
                    Sunday{
                      start
                      end
                    }
                }
                status{
                  pending
                  approved
                  deactivated
                }
                pockets
          }
        }
    `,
    updateBusiness: gql`
        mutation updateBusiness($userID: ID, $businessName:String, $dateEstablished:String, $emailAddress:String, $phoneNumber:String, $website:String, $businessType: String, $businessSubtype: String, $pocketID: ID, $address: Address, $latitude: Float, $longitude: Float, $businessTags: [String], $description: String){
            updateBusiness(userID: $userID, businessName:$businessName, dateEstablished:$dateEstablished, emailAddress:$emailAddress, phoneNumber:$phoneNumber, website:$website, businessType: $businessType, businessSubtype: $businessSubtype, pocketID:$pocketID, address: $address, latitude: $latitude, longitude: $longitude, businessTags: $businessTags, description: $description) {
                businessID
                businessName
                dateEstablished
                emailAddress
                phoneNumber
                website
                businessType
                businessSubtype
                address{
                    streetName
                    buildingNumber
                    unitNumber
                    city
                    region
                    postalCode
                }
                latitude
                longitude
                businessTags
                stripeID
                description
                hours{
                    Monday {
                      start
                      end
                    }
                    Tuesday{
                      start
                      end
                    }
                    Wednesday{
                      start
                      end
                    }
                    Thursday{
                      start
                      end
                    }
                    Friday{
                      start
                      end
                    }
                    Saturday{
                      start
                      end
                    }
                    Sunday{
                      start
                      end
                    }
                }
                status{
                    pending
                    approved
                    deactivated
                  }
                pockets
            }
        }
    `,
    deactivateBusiness: gql`
    mutation deactivateBusiness($userID: ID, $businessID: ID){
        deactivateBusiness(userID: $userID, businessID:$businessID) {
            businessID
            businessName
            dateEstablished
            emailAddress
            phoneNumber
            website
            businessType
            businessSubtype
            address{
                streetName
                buildingNumber
                unitNumber
                city
                region
                postalCode
            }
            latitude
            longitude
            businessTags
            stripeID
            description
            hours{
                Monday {
                  start
                  end
                }
                Tuesday{
                  start
                  end
                }
                Wednesday{
                  start
                  end
                }
                Thursday{
                  start
                  end
                }
                Friday{
                  start
                  end
                }
                Saturday{
                  start
                  end
                }
                Sunday{
                  start
                  end
                }
              }
            status{
                pending
                approved
                deactivated
              }
            pockets
        }
    }`,
    approveBusiness: gql`
    mutation approveBusiness($userID: ID, $businessID: ID){
        approveBusiness(userID: $userID, businessID:$businessID) {
            businessID
            businessName
            dateEstablished
            emailAddress
            phoneNumber
            website
            businessType
            businessSubtype
            address{
                streetName
                buildingNumber
                unitNumber
                city
                region
                postalCode
            }
            latitude
            longitude
            businessTags
            stripeID
            description
            hours{
                Monday {
                  start
                  end
                }
                Tuesday{
                  start
                  end
                }
                Wednesday{
                  start
                  end
                }
                Thursday{
                  start
                  end
                }
                Friday{
                  start
                  end
                }
                Saturday{
                  start
                  end
                }
                Sunday{
                  start
                  end
                }
              }
            status{
                pending
                approved
                deactivated
              }
            pockets
        }
    }
`,
createStripeLink: gql`
  mutation createStripeLink($userID: ID, $businessID: ID){
    createStripeLink(userID: $userID, businessID:$businessID) {
      created
      expires_at
      url
    }
  }
`,
}